package analizador_sintactico1;

public enum TipoToken {
    IDENTIFICADOR,

    // Palabras reservadas
    CLASS, FUN, VAR, FOR, IF, PRINT, RETURN, WHILE,
    TRUE, FALSE, NULL, THIS, SUPER, SELECT, FROM, DISTINCT,ELSE,IDENTIFIER,
    NUMBER, STRING, EQUALS, SEMICOLON, EXPRESSION,STATEMENT,
    EXPR_STMT,FOR_STMT,IF_STMT,PRINT_STMT,RETURN_STMT,WHILE_STMT,
    BLOCK,

    // Operadores y signos de puntuación
    COMA, PUNTO, PUNTO_COMA, PARENTESIS_ABRE, PARENTESIS_CIERRA,
    LLAVE_ABRE, LLAVE_CIERRA,
    ASIGNACION, IGUALDAD, DESIGUALDAD,
    MENOR, MENOR_O_IGUAL, MAYOR, MAYOR_O_IGUAL,
    SUMA, RESTA, DIVISION,
    AND, OR, NEGACION, ASTERISCO, CORCHETE_CIERRA, CORCHETE_ABRE, DOS_PUNTOS,

    // Literales
    NUMERO_ENTERO, NUMERO_DECIMAL, CADENA,

    // Fin de archivo
    EOF
}
